Repository 0xPolygonID/issuer-node, pull requests merged in 2023-02, with the labels that each got.

#176 docs: updating readme with vault token and private key
  README.md
Labels: documentation

#177 docs: warning m1 chip
  README.md
Labels: documentation

#179 feat: Upgrade go-schema-processor library to v1.1.0
  go.mod
  go.sum
  internal/api/server_test.go
Labels: improvement

#183 fix: hotfix agent type response
  internal/api/server.go
  internal/api/server_test.go
  internal/core/services/claims.go
Labels: bug

#187 fix: cache did not store/retrieve values properly
  infrastructure/local/docker-compose.yml
  internal/loader/cache.go
  pkg/cache/cache.go
  pkg/cache/memory.go
  pkg/cache/redis.go
Labels: bug

#189 docs: Suggest using unix style operating systems
  README.md
Labels: documentation
