Repository 0xPolygonID/issuer-node, pull requests merged in 2023-11, with the labels that each got.

#506 chore: add onchain rev status
  .env-issuer.sample
  Dockerfile
  Dockerfile-arm
  api/api.yaml
  api_ui/api.yaml
  cmd/issuer_initializer/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  go.mod
  go.sum
  internal/api/main_test.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/main_test.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/common/smart_contract.go
  internal/config/config.go
  internal/config/credential_status.go
  internal/core/domain/claim.go
  internal/core/ports/claims_service.go
  internal/core/ports/identity_service.go
  internal/core/ports/identity_state_repository.go
  internal/core/ports/revocation_service.go
  internal/core/ports/state_service.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/link.go
  internal/core/services/proof.go
  internal/core/services/revocation.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/core/services/tests/main_test.go
  internal/core/services/tests/notification_test.go
  internal/gateways/onchain_credential_status_resolver.go
  internal/repositories/identity_state.go
  pkg/blockchain/eth/state.go
  pkg/credentials/revocation_status/iden3_onchain_sparse_merkletree_proof2023_resolver.go
  pkg/credentials/revocation_status/iden3_reverse_sparse_merkletree_proof_resolver.go
  pkg/credentials/revocation_status/resolver.go
  pkg/credentials/revocation_status/resolver_test.go
  pkg/credentials/revocation_status/sparse_merkletree_proof_resolver.go
  pkg/credentials/revocation_status/utils.go
  pkg/reverse_hash/factory.go
  pkg/reverse_hash/reverse_hash.go
Labels: enhancement, backend

#512 fix: identities keytype in the database
  internal/db/schema/migrations/202310090829241_update_identities_table.sql
  internal/repositories/tests/claims_test.go
  internal/repositories/tests/link_test.go
Labels: bug, backend

#510 fix: solving broken ui for nullable expiration time
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api_ui/api.gen.go
Labels: bug, backend

#515 chore: return schema type in credential qr code endpoint and link qr code
  api_ui/api.yaml
  go.sum
  internal/api_ui/api.gen.go
  internal/api_ui/main_test.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
Labels: enhancement, backend

#521 fix: get link qr code was using old version of qr codes
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/main_test.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/services/link.go
  internal/core/services/tests/link_test.go
  pkg/link/link_state.go
  ui/src/adapters/api/credentials.ts
  ui/src/components/credentials/ClaimCredentialModal.tsx
Labels: bug, backend

#525 fix: qr codes is not mandatory in pending state
  pkg/link/link_state.go
  ui/src/adapters/api/credentials.ts
  ui/src/components/credentials/CredentialLinkQR.tsx
Labels: bug, frontend, backend

#538 chore: update fe dependencies
  ui/.prettierrc.json
  ui/.stylelintrc.json
  ui/package-lock.json
  ui/package.json
  ui/src/adapters/api/index.ts
  ui/src/adapters/json.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/adapters/parsers/index.ts
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/connections/IssueDirectlyButton.tsx
  ui/src/components/credentials/AttributeBreadcrumb.tsx
  ui/src/components/credentials/ClaimCredentialModal.tsx
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/Credentials.tsx
  ui/src/components/credentials/CredentialsTable.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinkDeleteModal.tsx
  ui/src/components/credentials/LinkDetails.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/ObjectAttributeValueTreeNode.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/layouts/SiderLayout.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemaTreeNode.tsx
  ui/src/components/schemas/SchemaViewer.tsx
  ui/src/components/schemas/Schemas.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/CredentialDeleteModal.tsx
  ui/src/components/shared/CredentialRevokeModal.tsx
  ui/src/components/shared/Detail.tsx
  ui/src/components/shared/ErrorResult.tsx
  ui/src/components/shared/FeedbackLink.tsx
  ui/src/components/shared/LogoLink.tsx
  ui/src/components/shared/NoResults.tsx
  ui/src/components/shared/SearchBox.tsx
  ui/src/components/shared/SiderLayoutContent.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/styles/index.scss
  ui/src/styles/theme.ts
  ui/src/utils/error.ts
Labels: dependencies

#539 feat: adding new changelog release tool
  .gitignore
  README.md
  tools/changelog/README.md
  tools/changelog/bin/linux-x86-64/changelog
  tools/changelog/bin/mac-arm64/changelog
  tools/changelog/input-sample.md
  tools/changelog/main.go
Labels: backend

#527 feat: add schema_type_description
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/core/domain/claim.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/db/schema/migrations/202311080942897_add_schema_type_description_to_claims.sql
  internal/repositories/claims.go
Labels: enhancement, backend

#542 Fix issuer UI restart
  Makefile
  README.md
  ui/scripts/deploy.sh
Labels: frontend

#553 feat: adding authentication session
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/ports/identity_service.go
  internal/core/services/connections.go
  internal/core/services/identity.go
  internal/db/schema/migrations/202311211436040_add_user_authentications_table.sql
  internal/db/tests/connections_fixture.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
Labels: enhancement, backend

#557 feat: Allow the selection of a custom IPFS gateway
  ui/src/adapters/api/schemas.ts
  ui/src/assets/icons/settings-01.svg
  ui/src/components/shared/SettingsModal.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/utils/constants.ts
Labels: frontend

#556 Release v2.3.2
  .github/issue-template.md
  .github/workflows/autoclose_stale_issues.yml
  Dockerfile-arm
  Makefile
  api_ui/api.yaml
  cmd/issuer_initializer/main.go
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/config/config.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/ports/identity_service.go
  internal/core/services/connections.go
  internal/core/services/identity.go
  internal/db/schema/migrations/202311211436040_add_user_authentications_table.sql
  internal/db/tests/connections_fixture.go
  internal/providers/vault.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
  ui/src/adapters/api/schemas.ts
  ui/src/assets/icons/settings-01.svg
  ui/src/components/shared/SettingsModal.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/utils/constants.ts
Labels: backend

#560 feat: Add config reload banner
  ui/src/components/shared/SettingsModal.tsx
Labels: frontend

#561 chore: improving README.md
  .env-issuer.sample
  README.md
  docs/assets/img/triangle-of-trust.png
Labels: documentation, do not merge
