Repository 0xPolygonID/issuer-node, pull requests merged in 2023-07, with the labels that each got.

#434 chore: update k8s docker images
  k8s/files/issuer-node-api-deployment.yaml
  k8s/files/issuer-node-api-ui-deployment.yaml
  k8s/files/issuer-node-notifications.yaml
  k8s/files/issuer-node-pending-publisher.yaml
  k8s/files/issuer-node-ui-deployment.yaml
Labels: enhancement, frontend, backend

#448 chore: update vault version
  k8s/files/vault-deployment.yaml
Labels: enhancement, backend

#449 fix: initializer
  cmd/issuer_initializer/main.go
  k8s/files/vault-configmap.yaml
Labels: bug, backend

#433 fix: Fix IPFS url bug when issuing a credential
  ui/src/adapters/json.ts
  ui/src/adapters/jsonSchemas.ts
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinkDetails.tsx
  ui/src/components/schemas/DownloadSchema.tsx
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
Labels: frontend

#450 fix: cannot create connection with empty unicode fields
  internal/core/services/identity.go
Labels: bug, backend

#451 chore: add init containers
  k8s/files/issuer-node-api-deployment.yaml
  k8s/files/issuer-node-api-ui-deployment.yaml
  k8s/files/issuer-node-notifications.yaml
  k8s/files/issuer-node-pending-publisher.yaml
  k8s/files/issuer-node-ui-deployment.yaml
Labels: improvement, backend

#452 fix: Fix date parsing and port the messageParser for Axios errors from the schema builder
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/issuer-state.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/adapters/parsers/index.ts
  ui/src/components/credentials/ObjectAttributeValueTreeNode.tsx
  ui/src/utils/error.ts
Labels: frontend

#453 fix: vault script
  k8s/files/vault-configmap.yaml
Labels: backend

#454 chore: update redis image
  k8s/files/redis-deployment.yaml
Labels: backend

#457 fix: upgrading go-ipfs-api for solving go-libp2p indirect vulnerability
  go.mod
  go.sum
Labels: improvement, backend

#458 chore: Emulate an ipfs gateway in go tests
  .github/workflows/checks.yml
  Makefile
  infrastructure/local/docker-compose-infra.yml
  infrastructure/local/httpd-test/httpd.conf
  infrastructure/local/test_data/schema/QmQVeb5dkz5ekDqBrYVVxBFQZoCbzamnmMUn9B8twCEgDL
  infrastructure/local/test_data/schema/QmTCpe3i3i5753DRyEnEw9jDSt6HhuFr43HwkKzQHRfsX9
  infrastructure/local/test_data/schema/QmcoHYA1K1xiFPHTUbDtVkV6HoKRCentZetfv4yLbrjwfY
  infrastructure/local/test_data/schema/QmeMevwUeD7o6hjfmdaeFD1q4L84hSDiRjeXZLi1bZK1My
  internal/api/main_test.go
  internal/api/server_test.go
  internal/api_ui/main_test.go
  internal/api_ui/server_test.go
  internal/jsonschema/schema_test.go
Labels: improvement, backend

#455 chore: update golang base image
  Dockerfile
  Dockerfile-arm
Labels: backend

#459 feat: adding version description and title to schemas
  api_ui/api.yaml
  go.mod
  go.sum
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/domain/schema.go
  internal/core/ports/schema_service.go
  internal/core/services/schema.go
  internal/core/services/tests/link_test.go
  internal/core/services/tests/main_test.go
  internal/core/services/tests/notification_test.go
  internal/core/services/tests/schema_test.go
  internal/db/schema/migrations/202307051116210_add_schemas_version_title_description_column.sql
  internal/repositories/schema.go
  internal/repositories/tests/schema_test.go
Labels: improvement, backend

#456 chore: Updates dependencies to the latest versions
  ui/.stylelintrc.json
  ui/package-lock.json
  ui/package.json
Labels: frontend

#460 feature: Add support for the schema version metadata
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/parsers/jsonSchemas.ts
  ui/src/components/schemas/ImportSchema.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemaViewer.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/domain/jsonSchema.ts
  ui/src/domain/schema.ts
Labels: frontend

#461 fix: How to build locally typo
  README.md
Labels: documentation

#462 feat: making title and description nullables in schemas
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/domain/schema.go
  internal/core/ports/schema_service.go
  internal/core/services/tests/link_test.go
  internal/core/services/tests/schema_test.go
  internal/db/schema/migrations/202307111216560_update_schemas_version_title_column.sql
  internal/repositories/schema.go
  internal/repositories/tests/schema_test.go
Labels: backend
