Repository 0xPolygonID/issuer-node, pull requests merged in 2023-08, with the labels that each got.

#435 feat: Add support for advanced props
  ui/src/adapters/parsers/forms.ts
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/ObjectAttributeForm.tsx
  ui/src/components/credentials/attributes/Boolean.tsx
  ui/src/components/credentials/attributes/Number.tsx
  ui/src/components/credentials/attributes/String.tsx
Labels: frontend

#476 feat: enabling RHS in the api and api-admin
  cmd/platform/main.go
  cmd/platform_ui/main.go
  internal/core/services/claims.go
  internal/core/services/revocation.go
  pkg/reverse_hash/reverse_hash.go
Labels: enhancement, backend

#474 Delete volumes
  .env-issuer.sample
  Makefile
  README.md
  cmd/issuer_initializer/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  go.mod
  go.sum
  infrastructure/local/.vault/config/policies.hcl
  infrastructure/local/.vault/scripts/init.sh
  internal/api/main_test.go
  internal/api_ui/main_test.go
  internal/config/config.go
  internal/core/services/tests/main_test.go
  internal/kms/main_test.go
  internal/kms/vaultPluginIden3KeyProvider_test.go
  internal/providers/vault.go
Labels: backend

#479 chore: add build revision information
  cmd/issuer_initializer/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  internal/buildinfo/buildinfo.go
Labels: enhancement, backend

#475 chore: add k8s kustomize for mumbai and mainnet
  k8s/Readme.md
  k8s/files/Makefile
  k8s/files/Readme.md
  k8s/files/base/ingress.yaml
  k8s/files/base/issuer-node-api-configmap.yaml
  k8s/files/base/issuer-node-api-deployment.yaml
  k8s/files/base/issuer-node-api-service.yaml
  k8s/files/base/issuer-node-api-ui-configmap.yaml
  k8s/files/base/issuer-node-api-ui-deployment.yaml
  k8s/files/base/issuer-node-api-ui-service.yaml
  k8s/files/base/issuer-node-notifications.yaml
  k8s/files/base/issuer-node-pending-publisher.yaml
  k8s/files/base/issuer-node-ui-configmap.yaml
  k8s/files/base/issuer-node-ui-deployment.yaml
  k8s/files/base/issuer-node-ui-service.yaml
  k8s/files/base/kustomization.yaml
  k8s/files/base/postgres-configmap.yaml
  k8s/files/base/postgres-deployment.yaml
  k8s/files/base/postgres-pv.yaml
  k8s/files/base/postgres-service.yaml
  k8s/files/base/redis-deployment.yaml
  k8s/files/base/redis-service.yaml
  k8s/files/base/vault-configmap.yaml
  k8s/files/base/vault-deployment.yaml
  k8s/files/base/vault-pv.yaml
  k8s/files/base/vault-service.yaml
  k8s/files/issuer-node-api-deployment.yaml
  k8s/files/issuer-node-api-ui-deployment.yaml
  k8s/files/issuer-node-notifications.yaml
  k8s/files/issuer-node-pending-publisher.yaml
  k8s/files/mainnet/ingress-patch.yaml
  k8s/files/mainnet/issuer-node-api-configmap-patch.yaml
  k8s/files/mainnet/issuer-node-api-ui-configmap-patch.yaml
  k8s/files/mainnet/issuer-node-ui-configmap-patch.yaml
  k8s/files/mainnet/kustomization.yaml
  k8s/files/mumbai/ingress-patch.yaml
  k8s/files/mumbai/issuer-node-api-configmap-patch.yaml
  k8s/files/mumbai/issuer-node-api-ui-configmap-patch.yaml
  k8s/files/mumbai/issuer-node-ui-configmap-patch.yaml
  k8s/files/mumbai/kustomization.yaml
  k8s/files/vault-pv.yaml
Labels: enhancement, backend

#485 fix: send credential id in 409 authentication callback
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
Labels: backend
