Repository 0xPolygonID/issuer-node, pull requests merged in 2023-04, with the labels that each got.

#281 feat: filter schemas by issuerDID
  internal/api_admin/server.go
  internal/core/ports/schema_admin_service.go
  internal/core/ports/schema_repository.go
  internal/core/services/link.go
  internal/core/services/schema_admin.go
  internal/repositories/schema-inmemory.go
  internal/repositories/schema.go
  internal/repositories/tests/schema_test.go
Labels: improvement, backend

#273 Issuer can view connection details
  ui/src/adapters/api/connections.ts
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/Connections.tsx
  ui/src/components/connections/ConnectionsRowDropdown.tsx
  ui/src/components/shared/Router.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/routes.ts
  ui/src/utils/constants.ts
Labels: frontend

#285 docs: improving documentation endpoint names and order
  api_ui/api.yaml
  api_ui/spec.html
  internal/api_admin/api.gen.go
Labels: documentation, backend

#286 feat: adding state status endpoint
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
Labels: documentation, enhancement, backend

#284 Fix: Don't show never expired credentials as expired ones.
  internal/api_admin/server_test.go
  internal/repositories/claims.go
Labels: improvement, backend

#290 fix: credential creation expiration wrong timestamp format
  api_ui/api.yaml
  internal/api_admin/api.gen.go
Labels: bug, documentation, backend

#280 Endpoint to get credential links
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/link.go
  internal/core/domain/link_test.go
  internal/core/ports/link_repository.go
  internal/core/ports/link_service.go
  internal/core/services/link.go
  internal/repositories/link_repository.go
  internal/repositories/tests/link_test.go
Labels: documentation, enhancement, backend

#291 docs: improve create credential example
  api_ui/api.yaml
  internal/api_admin/api.gen.go
Labels: documentation, backend

#288 feat: adding get state transactions endpoint
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/identity_service.go
  internal/core/ports/identity_state_repository.go
  internal/core/services/identity.go
  internal/repositories/identity_state.go
Labels: documentation, enhancement, backend

#292 Consolidated functions, constants and types - Refactor domain
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/adapters/parsers/schemas.ts
  ui/src/adapters/parsers/serializers.ts
  ui/src/adapters/schemas.ts
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/Connections.tsx
  ui/src/components/credentials/CredentialAttribute.tsx
  ui/src/components/credentials/Credentials.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinkTable.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemaTree.tsx
  ui/src/components/schemas/SchemaTreeNode.tsx
  ui/src/components/schemas/SchemaViewer.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/domain/env.ts
  ui/src/domain/index.ts
  ui/src/domain/json.ts
  ui/src/domain/jsonSchema.ts
  ui/src/utils/constants.ts
Labels: frontend

#283 The issuer can search and see credentials in a connection details
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/ConnectionDetailsRowDropdown.tsx
  ui/src/components/connections/IssueDirectlyButton.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/shared/Detail.tsx
  ui/src/components/shared/SiderLayoutContent.tsx
  ui/src/components/shared/TableCard.tsx
  ui/src/utils/constants.ts
Labels: frontend

#289 Issuer can delete a connection
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/ConnectionDetailsRowDropdown.tsx
  ui/src/components/connections/ConnectionsRowDropdown.tsx
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/shared/Detail.tsx
  ui/src/components/shared/Router.tsx
  ui/src/utils/constants.ts
Labels: frontend

#294 Pid 432 endpoint to retry failed publish state transactions
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/core/ports/identity_repository.go
  internal/core/ports/identity_service.go
  internal/core/ports/identity_state_repository.go
  internal/core/ports/publisher.go
  internal/core/services/identity.go
  internal/gateways/publisher.go
  internal/repositories/identity.go
  internal/repositories/identity_state.go
Labels: documentation, enhancement, backend

#296 Escape SQL params when searching over credentials
  api/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/core/ports/claims_service.go
  internal/core/services/proof.go
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
Labels: improvement, backend

#300 fix get links endpoint when filtering by exceeded
  internal/api_admin/server_test.go
  internal/repositories/link_repository.go
  internal/repositories/tests/link_test.go
Labels: bug, backend

#302 Update issuer node to support blockchain main net
  .env-api.sample
  cmd/issuer_initializer/main.go
  infrastructure/local/docker-compose.yml
  internal/config/config.go
  pkg/protocol/verify.go
Labels: improvement, backend

#301 feat: adding send push notification with pubsub
  Makefile
  cmd/admin/main.go
  cmd/notifications/main.go
  infrastructure/local/docker-compose.yml
  internal/api_admin/main_test.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/notification.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/ports/notification_service.go
  internal/core/services/claims.go
  internal/core/services/connections.go
  internal/core/services/notification.go
  internal/core/services/tests/notification_test.go
  internal/gateways/notification.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
  pkg/notifications/messages.go
  pkg/notifications/push.go
  pkg/pubsub/mock.go
  pkg/pubsub/pubsub.go
  pkg/pubsub/redis.go
Labels: documentation, enhancement, backend

#304 chore: updating contract-abi
  go.mod
  go.sum
  internal/core/services/proof.go
  internal/core/services/revocation.go
  internal/gateways/publisher_gateway.go
  internal/providers/blockchain/eth.go
  pkg/blockchain/eth/client.go
  pkg/blockchain/eth/contracts.go
  pkg/protocol/packagemanager.go
  pkg/protocol/verify.go
Labels: backend

#306 Do not throw CreateCredential event for mtProof credentials
  internal/api/server_test.go
  internal/api_admin/server_test.go
  internal/core/services/claims.go
  pkg/pubsub/mock.go
Labels: improvement, backend

#298 Issuer can view submitted credential links
  ui/src/adapters/api/credentials.ts
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/credentials/Credentials.tsx
  ui/src/components/credentials/LinkTable.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/domain/credential.ts
Labels: frontend

#307 Create a new state for mtp proofs links in get link qr code
  api_ui/api.yaml
  internal/api/server.go
  internal/api/server_test.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/claim.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/db/schema/migrations/202304121507181_add_linid_to_claims_table.sql
  internal/repositories/claims.go
  internal/repositories/link_repository.go
  internal/repositories/tests/claims_test.go
  internal/repositories/tests/link_test.go
  pkg/link/link_state.go
Labels: backend

#308 feat: sending push notification for new connections
  .golangci.yml
  cmd/admin/main.go
  cmd/issuer_initializer/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  internal/api/server_test.go
  internal/api_admin/server_test.go
  internal/core/domain/proof.go
  internal/core/ports/claims_service.go
  internal/core/ports/notification_service.go
  internal/core/services/identity.go
  internal/core/services/notification.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/notification_test.go
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
  pkg/notifications/messages.go
  pkg/pubsub/pubsub.go
Labels: enhancement, backend

#309 chore: renaming credential attributes for credential subject
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server_test.go
  internal/core/services/tests/link_test.go
Labels: documentation, backend

#311 fix: change state to failed when publisher fails
  internal/gateways/publisher.go
Labels: bug, backend

#313 feat: adding multi depth credential subject
  api_ui/api.yaml
  go.mod
  go.sum
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/link.go
  internal/core/ports/link_service.go
  internal/core/services/link.go
  internal/core/services/tests/link_test.go
  internal/repositories/link_repository.go
  internal/repositories/tests/claims_test.go
  internal/repositories/tests/link_test.go
Labels: documentation, enhancement, backend

#314 feat: adding agent endpoint in admin api
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
Labels: documentation, backend

#315 Pid 595 add pending publisher component to make file
  Makefile
Labels: enhancement, backend

#316 fix: link expiration link validation
  api_ui/api.yaml
  internal/api_admin/server.go
Labels: bug

#318 Replaced old to previous
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/credentials/IssuedTable.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/SearchBox.tsx
Labels: frontend

#303 Issuer can revoke and delete a credential
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/assets/icons/alert-triangle.svg
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/credentials/IssuedTable.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/CredentialDeleteModal.tsx
  ui/src/components/shared/CredentialRevokeModal.tsx
  ui/src/components/shared/SearchBox.tsx
  ui/src/domain/credential.ts
  ui/src/domain/index.ts
  ui/src/styles/theme.ts
  ui/src/styles/variables.module.scss
  ui/src/utils/constants.ts
Labels: frontend

#320 Flow to delete link
  ui/src/adapters/api/credentials.ts
  ui/src/components/credentials/LinkDeleteModal.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/domain/credential.ts
Labels: frontend

#317 fix: add notifications when a claim is created from Link QR Code
  cmd/admin/main.go
  internal/api/server_test.go
  internal/api_admin/server_test.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
Labels: bug, backend

#321 feat: avoid sending notifications when updating connections
  internal/core/services/identity.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
Labels: improvement, backend

#319 feat: validate link credential subject against schema
  go.mod
  go.sum
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/common/helpers.go
  internal/common/helpers_test.go
  internal/core/services/link.go
  internal/jsonschema/schema.go
  internal/jsonschema/schema_test.go
Labels: improvement, backend

#323 Pid 567 send notification when mpt credentials are published
  cmd/admin/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/gateways/publisher.go
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
Labels: enhancement, backend

#297 Issuer can submit a credential link issuance
  ui/README.md
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/json.ts
  ui/src/adapters/jsonSchemas.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/adapters/parsers/jsonSchemas.ts
  ui/src/adapters/parsers/serializers.ts
  ui/src/assets/icons/chevron-right.svg
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/credentials/AttributeBreadcrumb.tsx
  ui/src/components/credentials/CredentialAttribute.tsx
  ui/src/components/credentials/CredentialSubjectForm.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/ScanCredentialLink.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/credentials/attributes/Boolean.tsx
  ui/src/components/credentials/attributes/Number.tsx
  ui/src/components/credentials/attributes/String.tsx
  ui/src/components/schemas/Attribute.tsx
  ui/src/domain/credential.ts
  ui/src/domain/index.ts
  ui/src/domain/json.ts
  ui/src/domain/jsonSchema.ts
  ui/src/domain/schema.ts
  ui/src/routes.ts
  ui/src/styles/index.scss
  ui/src/utils/browser.ts
  ui/src/utils/constants.ts
Labels: frontend

#324 Rename change api admin for api UI
  Makefile
  README.md
  api/api.yaml
  api_ui/api.yaml
  api_ui/config-oapi-codegen.yaml
  cmd/notifications/main.go
  cmd/platform_ui/main.go
  infrastructure/local/docker-compose.yml
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/api.gen.go
  internal/api_ui/api_test.go
  internal/api_ui/main_test.go
  internal/api_ui/middleware.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/common/util.go
  internal/config/config.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/link.go
  pkg/pubsub/redis.go
Labels: documentation, backend

#326 fix: get links credential subject returning wrong data
  internal/repositories/link_repository.go
Labels: bug, backend

#312 Test and small changes in pubsub
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  go.mod
  go.sum
  internal/api/server_test.go
  internal/api_ui/server_test.go
  internal/core/event/event.go
  internal/core/ports/notification_service.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/link.go
  internal/core/services/notification.go
  internal/core/services/tests/notification_test.go
  internal/gateways/publisher.go
  pkg/pubsub/pubsub.go
  pkg/pubsub/redis.go
  pkg/pubsub/redis_test.go
Labels: enhancement, backend

#325 fix: returning null instead of not returning the property
  api_ui/api.yaml
  internal/api_ui/api.gen.go
Labels: documentation, backend

#328 Chore: Rename schema admin service to schema service
  cmd/platform_ui/main.go
  internal/api_ui/main_test.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/schema_service.go
  internal/core/services/schema.go
  internal/core/services/tests/link_test.go
  internal/core/services/tests/schema_test.go
Labels: backend

#332 feat: Include schema type and schema url fields in credencial entity responses
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server_test.go
Labels: enhancement, backend

#333 feat: adding proofTypes in link
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server_test.go
Labels: documentation, backend

#331 feat: adding revocation status endpoint in api-ui
  api_ui/api.yaml
  cmd/platform_ui/main.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
Labels: documentation, enhancement, backend

#322 New section Issuer state
  .env-ui.sample
  README.md
  ui/.env.sample
  ui/scripts/deploy.sh
  ui/src/adapters/api/issuer-state.ts
  ui/src/adapters/env.ts
  ui/src/assets/icons/switch-horizontal.svg
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssuedTable.tsx
  ui/src/components/credentials/LinkDeleteModal.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/ScanCredentialLink.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/schemas/ImportSchema.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/CredentialDeleteModal.tsx
  ui/src/components/shared/CredentialRevokeModal.tsx
  ui/src/components/shared/Router.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/components/shared/TableCard.tsx
  ui/src/components/shared/UserDisplay.tsx
  ui/src/contexts/Env.tsx
  ui/src/contexts/IssuerState.tsx
  ui/src/domain/env.ts
  ui/src/domain/index.ts
  ui/src/domain/issuer-state.ts
  ui/src/env.d.ts
  ui/src/index.tsx
  ui/src/routes.ts
  ui/src/utils/constants.ts
Labels: frontend

#335 feat: adding createdAt and schemaHash in link response
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server_test.go
Labels: documentation, improvement, backend

#338 chore: send only one push notif. for all the pending credentials
  internal/core/event/event.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/notification.go
  internal/core/services/tests/notification_test.go
  internal/gateways/publisher.go
Labels: enhancement, backend

#336 feat: adding get credential qr code endpoint in api_ui
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
Labels: documentation, enhancement, backend

#340 chore: improving create credential errors
  internal/api/server.go
  internal/api_ui/server.go
  internal/core/services/claims.go
  pkg/schema/schema.go
Labels: improvement, backend

#330 Holder can authenticate & add credential via QR code for credential link
  ui/package-lock.json
  ui/package.json
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/adapters/api/issuer-state.ts
  ui/src/adapters/api/schemas.ts
  ui/src/components/credentials/ClaimCredentialModal.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/LinkDeleteModal.tsx
  ui/src/components/credentials/ScanCredentialLink.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/layouts/FullWidthLayout.tsx
  ui/src/components/shared/Router.tsx
  ui/src/domain/credential.ts
  ui/src/domain/index.ts
  ui/src/routes.ts
  ui/src/styles/index.scss
  ui/src/styles/variables.module.scss
  ui/src/utils/browser.ts
Labels: frontend

#349 feat: adding userID field to credential
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server_test.go
  pkg/pubsub/redis_test.go
Labels: documentation, backend

#346 fix: returning an error when trying to create qr code for invalid link
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/services/link.go
Labels: bug, backend

#342 Issuer can choose SIG and/or MTP proof types for credential issuance
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/components/credentials/CredentialSubjectForm.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/domain/credential.ts
  ui/src/styles/index.scss
Labels: frontend

#345 Fixes, consolidates & expands documentation & config with up-to-date functionality.
  .github/workflows/checks.yml
  .github/workflows/deploy.yml
  .github/workflows/golangci-lint.yml
  Makefile
  README.md
  infrastructure/local/docker-compose-infra.yml
  infrastructure/local/docker-compose.yml
  ui/.env.sample
Labels: documentation

#351 feat: removing type from credentialSubject in credential response
  api_ui/api.yaml
  internal/api_ui/responses.go
  internal/api_ui/server_test.go
Labels: documentation, backend

#350 Polygon ID favicon in api and api UI
  Makefile
  api/api.yaml
  api/polygon.png
  api/spec.html
  api_ui/api.yaml
  api_ui/polygon.png
  api_ui/spec.html
  go.mod
  go.sum
  internal/api/api.gen.go
  internal/api/server.go
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
Labels: enhancement, backend

#354 feat: adding credential expiration in link response
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
Labels: documentation, backend

#356 fix: not returning mtp sig in connection and credentials
  internal/api_ui/responses.go
  internal/repositories/claims.go
  internal/repositories/connections.go
Labels: bug, backend

#353 Issuer can submit a credential direct issuance
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/connections/IssueDirectlyButton.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/styles/index.scss
  ui/src/utils/constants.ts
Labels: frontend

#357 Updated feeback link.
  ui/src/utils/constants.ts
Labels: frontend

#359 Issuer state flow
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/contexts/IssuerState.tsx
Labels: frontend

#362 fix: revoking credential overrides mtp
  internal/repositories/claims.go
Labels: bug, backend

#363 Add zod support to buildAPIError and parse elements of lists individually
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/adapters/api/issuer-state.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/parsers/index.ts
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/domain/connection.ts
  ui/src/utils/types.ts
Labels: frontend
