Repository 0xPolygonID/issuer-node, pull requests merged in 2023-03, with the labels that each got.

#191 User interface skeleton
  .github/CODEOWNERS
  Makefile
  infrastructure/local/docker-compose.yml
  ui/.gitignore
  ui/Dockerfile
  ui/deployment/nginx.conf
  ui/package-lock.json
  ui/package.json
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/logo192.png
  ui/public/logo512.png
  ui/public/manifest.json
  ui/public/robots.txt
  ui/scripts/deploy.sh
  ui/src/App.css
  ui/src/App.js
  ui/src/App.test.js
  ui/src/index.css
  ui/src/index.js
  ui/src/logo.svg
  ui/src/reportWebVitals.js
  ui/src/setupTests.js
Labels: frontend

#200 feat: adding schemas table
  internal/db/schema/migrations/20230303114429_add_schemas_table.sql
Labels: enhancement, backend

#202 feat: auth qr code and authentication callback
  .env-api.sample
  .golangci.yml
  api_ui/api.yaml
  cmd/admin/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  go.mod
  go.sum
  internal/api/server_test.go
  internal/api_admin/api.gen.go
  internal/api_admin/main_test.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/config/config.go
  internal/core/domain/connection.go
  internal/core/ports/connections_repository.go
  internal/core/ports/identity_service.go
  internal/core/ports/session_repository.go
  internal/core/services/identity.go
  internal/core/services/tests/identity_test.go
  internal/db/schema/migrations/20230308093840_add_connections_table.sql
  internal/repositories/connections.go
  internal/repositories/session.go
  internal/repositories/tests/connections_test.go
  pkg/credentials/circuits/authV2/authV2.json
  pkg/loaders/circuits.go
Labels: enhancement, backend

#204 feat: adding delete connection
  api_ui/api.yaml
  cmd/admin/main.go
  internal/api_admin/api.gen.go
  internal/api_admin/main_test.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/connections.go
  internal/core/services/identity.go
  internal/db/tests/connections_fixture.go
  internal/db/tests/fixture.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
Labels: enhancement, backend

#210 chore: moving from Iden3SparseMerkleProof to Iden3SparseMerkleTreeProof
  internal/core/domain/claim.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/schema.go
  internal/db/schema/migrations/20230309164801_update_claims_mtp_proof_column.sql
Labels: improvement, backend

#211 fix: downgrading kin-openapi library
  go.mod
  go.sum
Labels: bug, backend

#212 fix: downgrading open api code gen
  go.mod
  go.sum
Labels: bug, backend

#213 feat: Import json schema
  api_ui/api.yaml
  cmd/admin/main.go
  internal/api/api.gen.go
  internal/api_admin/api.gen.go
  internal/api_admin/main_test.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/claim.go
  internal/core/domain/schema.go
  internal/core/ports/schema_admin_service.go
  internal/core/ports/schema_repository.go
  internal/core/ports/schema_service.go
  internal/core/services/schema_admin.go
  internal/core/services/tests/schema_admin_test.go
  internal/db/schema/migrations/20230303114429_add_schemas_table.sql
  internal/jsonschema/schema.go
  internal/loader/cache.go
  internal/loader/file.go
  internal/log/log.go
  internal/repositories/schema-inmemory.go
  internal/repositories/schema.go
  internal/repositories/tests/schema_test.go
Labels: documentation, enhancement, backend

#214 feat: add create credential
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
Labels: documentation, enhancement, backend

#215 chore: check did when ui api starts
  cmd/admin/main.go
  internal/core/ports/identity_repository.go
  internal/core/ports/identity_service.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/proof.go
  internal/core/services/tests/identity_test.go
  internal/gateways/publisher.go
  internal/repositories/identity.go
Labels: enhancement, backend

#216 feat: adding admin get credential
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/services/schema.go
  pkg/schema/schema.go
Labels: documentation, enhancement, backend

#217 feat: add revocation endpoint
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
Labels: documentation, enhancement, backend

#220 feat: Get schema endpoint
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/schema_admin_service.go
  internal/core/ports/schema_repository.go
  internal/core/services/claims.go
  internal/core/services/schema_admin.go
  internal/db/tests/claims_fixture.go
  internal/db/tests/fixture.go
  internal/repositories/schema-inmemory.go
  internal/repositories/schema.go
  internal/repositories/tests/schema_test.go
Labels: documentation, enhancement, backend

#219 feat: adding delete credential
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/repositories/claims.go
Labels: documentation, enhancement, backend

#221 feat: adding get connection endpoint
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/claims_service.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/claims.go
  internal/core/services/connections.go
  internal/repositories/claims.go
  internal/repositories/connections.go
  pkg/schema/schema.go
Labels: documentation, enhancement, backend

#222 feat: Get All Schemas endpoint
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/schema_admin_service.go
  internal/core/ports/schema_repository.go
  internal/core/services/schema_admin.go
  internal/repositories/claims.go
  internal/repositories/identity_state.go
  internal/repositories/mt.go
  internal/repositories/revocation.go
  internal/repositories/schema-inmemory.go
  internal/repositories/schema.go
Labels: documentation, enhancement, backend

#224 Pid 400 add make file command for setting vault token
  Makefile
  README.md
  infrastructure/local/docker-compose.yml
Labels: backend

#229 fix: solving cors errors for frontend UI
  cmd/admin/main.go
Labels: bug, improvement, backend

#228 feat: improving auth security
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/identity_service.go
  internal/core/services/identity.go
Labels: improvement, backend

#230 Pid 413 add GitHub actions ci cd to aws testing environment
  .github/workflows/deploy.yml
  Makefile
Labels: backend

#227 docs: shape open api structure
  api_ui/api.yaml
  api_ui/spec.html
  internal/api_admin/api.gen.go
Labels: documentation, backend

#226 chore: add issuer initializer
  Makefile
  README.md
  cmd/issuer_initializer/main.go
Labels: backend

#233 fix: returning valid error message in invalid requests
  cmd/admin/main.go
  internal/api_admin/main_test.go
  internal/api_admin/server_test.go
Labels: improvement, backend

#235 fix make command for issuer did creation
  Makefile
  README.md
  infrastructure/local/docker-compose.yml
Labels: backend

#237 chore: Refactor schema service service into a library
  cmd/admin/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_admin/server_test.go
  internal/core/ports/schema_service.go
  internal/core/services/claims.go
  internal/core/services/schema.go
  internal/core/services/tests/identity_test.go
  pkg/schema/schema.go
Labels: backend

#242 docs: adding open api examples
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server_test.go
Labels: documentation, backend

#251 feat: add publish identity state
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/core/ports/claims_repository.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/gateways/publisher.go
  internal/repositories/claims.go
  pkg/blockchain/eth/client.go
Labels: documentation, enhancement, backend

#241 Parse UI env variables with zod
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/env.ts
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/LinkTable.tsx
  ui/src/components/credentials/ScanCredentialLink.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/schemas/ImportSchema.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/UserDisplay.tsx
  ui/src/contexts/env.tsx
  ui/src/domain/index.ts
  ui/src/index.tsx
  ui/src/utils/constants.ts
Labels: frontend

#253 feat: adding revoke all claims of a connection
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
Labels: documentation, enhancement, backend

#247 chore: using issuerDID in connection deletion
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/connections.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
Labels: improvement, backend

#249 feat: adding delete credentials of connection
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/connections.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
Labels: documentation, enhancement, backend

#254 feat: Get Credentials endpoint
  api_ui/api.yaml
  internal/api/server.go
  internal/api/server_test.go
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/schema.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/core/services/proof.go
  internal/db/tests/claims_fixture.go
  internal/repositories/claims.go
  internal/repositories/connections.go
  internal/repositories/ftsutil.go
  internal/repositories/ftsutil_test.go
  internal/repositories/schema.go
  internal/repositories/schema_test.go
  internal/repositories/tests/schema_test.go
Labels: documentation, enhancement, backend

#258 Pid 180 create credential link issue credential link
  api_ui/api.yaml
  cmd/admin/main.go
  internal/api_admin/api.gen.go
  internal/api_admin/main_test.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/link.go
  internal/core/ports/link_repository.go
  internal/core/ports/link_service.go
  internal/core/services/link.go
  internal/db/schema/migrations/20230322114550_add_links_table.sql
  internal/repositories/link_repository.go
  internal/repositories/tests/link_test.go
Labels: documentation, enhancement, backend

#262 DRYing up schema details & preview.
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/JSONHighlighter.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemaViewer.tsx
  ui/src/styles/index.scss
  ui/src/utils/adapters.ts
  ui/src/utils/constants.ts
Labels: frontend

#256 Improve organization of adapters parsers types and their files
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/json.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/adapters/parsers/schemas.ts
  ui/src/adapters/parsers/serializers.ts
  ui/src/adapters/schemas.ts
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/LinkTable.tsx
  ui/src/components/credentials/ScanCredentialLink.tsx
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/BackButton.tsx
  ui/src/components/shared/CheckItems.tsx
  ui/src/components/shared/ErrorMessage.tsx
  ui/src/contexts/env.tsx
  ui/src/domain/index.ts
  ui/src/styles/theme.ts
  ui/src/utils/adapters.ts
  ui/src/utils/browser.ts
  ui/src/utils/constants.ts
  ui/src/utils/error.ts
  ui/src/utils/forms.ts
  ui/src/utils/types.ts
Labels: frontend

#265 feat: delete credential link
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/link_repository.go
  internal/core/ports/link_service.go
  internal/core/services/link.go
  internal/repositories/link_repository.go
  internal/repositories/tests/link_test.go
Labels: documentation, enhancement, backend

#257 feat: adding the option to revoke & delete credentials in del conn endpoint
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/connections_service.go
  internal/core/services/connections.go
Labels: documentation, enhancement, backend

#267 feat: adding get connections with credentials
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/domain/claim.go
  internal/core/domain/connection.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/connections.go
  internal/repositories/claims.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
  pkg/schema/schema.go
Labels: documentation, enhancement, backend

#266 feat: add issuer did to delete link
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/link_repository.go
  internal/core/ports/link_service.go
  internal/core/services/link.go
  internal/repositories/link_repository.go
  internal/repositories/tests/link_test.go
Labels: backend

#268 feat: add configurable cache for schemas
  .env-api.sample
  .env-issuer.sample
  cmd/admin/main.go
  cmd/platform/main.go
  internal/config/config.go
Labels: enhancement, backend

#263 feat: add activate-deactivate credential link
  api_ui/api.yaml
  internal/api_admin/api.gen.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/core/ports/link_service.go
  internal/core/services/link.go
  internal/repositories/link_repository.go
  internal/repositories/tests/link_test.go
Labels: documentation, enhancement, backend

#275 feat: add link QR Code generation and callback
  api_ui/api.yaml
  cmd/admin/main.go
  internal/api/api.gen.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_admin/api.gen.go
  internal/api_admin/responses.go
  internal/api_admin/server.go
  internal/api_admin/server_test.go
  internal/config/config.go
  internal/core/domain/link.go
  internal/core/ports/claims_service.go
  internal/core/ports/identity_service.go
  internal/core/ports/link_repository.go
  internal/core/ports/link_service.go
  internal/core/ports/session_repository.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/db/schema/migrations/20230329153017_add_column_issued_to_links_table.sql
  internal/repositories/link_repository.go
  internal/repositories/session.go
  internal/repositories/tests/link_test.go
  pkg/link/link_state.go
Labels: enhancement, backend
