Repository 0xPolygonID/issuer-node, pull requests merged in 2023-12, with the labels that each got.

#567 chore: update github actions
  .github/workflows/dockerhub-dev.yml
  .github/workflows/dockerhub-main.yml
Labels: enhancement, backend

#575 feat: Pagination in get credentials api endpoint
  api_ui/api.yaml
  internal/api/server.go
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/core/services/notification.go
  internal/core/services/proof.go
  internal/db/tests/claims_fixture.go
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
Labels: backend

#579 chore: add health check to docker containers
  infrastructure/local/docker-compose-infra.yml
  infrastructure/local/docker-compose.yml
Labels: enhancement

#552 feat: Backward support for old raw QRCodes in API UI
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/main_test.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_service.go
  internal/core/ports/identity_service.go
  internal/core/ports/link_service.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/link.go
Labels: backend

#585 Fix/use time rfc3339nano
  internal/core/services/claims.go
  internal/timeapi/time.go
  internal/timeapi/time_test.go
Labels: backend

#581 feat: support refresh service
  .golangci.yml
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/domain/link.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/ports/link_service.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/db/schema/migrations/20231214192507_add_refresh_service_to_link_table.sql
  internal/db/tests/claims_fixture.go
  internal/repositories/claims.go
  internal/repositories/link_repository.go
  internal/repositories/tests/claims_test.go
  internal/repositories/tests/link_test.go
Labels: backend

#586 feat: Ability to set order in Get Credentials endpoint
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_service.go
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
  internal/sqltools/orderbyfilter.go
  internal/sqltools/orderbyfilter_test.go
Labels: backend

#580 feat: adding paging to the getConnections endpoint
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/claims.go
  internal/core/services/connections.go
  internal/repositories/claims.go
  internal/repositories/connections.go
  internal/repositories/tests/claims_test.go
  internal/repositories/tests/connections_test.go
  pkg/pagination/pagination.go
Labels: backend
