Repository 0xPolygonID/issuer-node, pull requests merged in 2023-05, with the labels that each got.

#368 fix: qr code endpoints should no require basic auth
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server_test.go
Labels: bug, backend

#366 Added CredentialQR.
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/env.ts
  ui/src/components/credentials/CredentialIssuedQR.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/CredentialQR.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/components/shared/UserDisplay.tsx
  ui/src/contexts/Env.tsx
  ui/src/domain/env.ts
Labels: enhancement, frontend

#365 Added page for adding a directly-issued credential via QR code
  ui/deployment/nginx.conf
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/env.ts
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/CredentialIssuedQR.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/CredentialQR.tsx
  ui/src/components/shared/Detail.tsx
  ui/src/components/shared/Router.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/components/shared/UserDisplay.tsx
  ui/src/contexts/Env.tsx
  ui/src/domain/credential.ts
  ui/src/domain/env.ts
  ui/src/domain/index.ts
  ui/src/routes.ts
  ui/src/styles/index.scss
Labels: frontend

#371 Add support for new description schema types format
  ui/src/adapters/api/credentials.ts
  ui/src/components/credentials/CredentialQR.tsx
  ui/src/domain/credential.ts
Labels: frontend

#374 fix: wrong verifiable credential id in api-ui
  internal/core/services/claims.go
Labels: bug, backend

#381 feat: sync selectors with url
  ui/src/adapters/parsers/forms.ts
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/routes.ts
  ui/src/utils/constants.ts
Labels: frontend

#376 feat: Filter connections by substrings of a did.
  internal/api_ui/server_test.go
  internal/repositories/connections.go
  internal/repositories/ftsutil.go
  internal/repositories/ftsutil_test.go
  internal/repositories/tests/connections_test.go
Labels: enhancement, backend

#375 refactor: Remove Result types and model Error domain
  ui/README.md
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/adapters/api/issuer-state.ts
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/index.ts
  ui/src/adapters/json.ts
  ui/src/adapters/jsonSchemas.ts
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/connections/ConnectionDetails.tsx
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/CredentialIssuedQR.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/CredentialsTable.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/LinkDeleteModal.tsx
  ui/src/components/credentials/LinkDetails.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/SelectSchema.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/schemas/ImportSchema.tsx
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/CredentialDeleteModal.tsx
  ui/src/components/shared/CredentialRevokeModal.tsx
  ui/src/components/shared/Explainer.tsx
  ui/src/contexts/Env.tsx
  ui/src/contexts/IssuerState.tsx
  ui/src/domain/error.ts
  ui/src/domain/index.ts
  ui/src/utils/browser.ts
  ui/src/utils/error.ts
  ui/src/utils/localStorage.ts
Labels: frontend

#379 feat: Handling for configurable UI app-wide warning notification.
  .env-ui.sample
  ui/.env.sample
  ui/scripts/deploy.sh
  ui/src/adapters/env.ts
  ui/src/components/shared/Router.tsx
  ui/src/components/shared/SiderLayoutContent.tsx
  ui/src/domain/env.ts
  ui/src/styles/index.scss
Labels: frontend

#387 Fix merge issue
  ui/src/components/shared/SiderLayoutContent.tsx
Labels: frontend

#386 fix: update makefile command
  Makefile
Labels: bug, backend

#391 fix: empty warning notification with absent config
  ui/src/components/shared/SiderLayoutContent.tsx
Labels: frontend

#389 docs: updating schema examples
  docs/examples/schemas/json-ld/exampleBoolean.json-ld
  docs/examples/schemas/json-ld/exampleDate.json-ld
  docs/examples/schemas/json-ld/exampleEmployee.json-ld
  docs/examples/schemas/json-ld/exampleInteger.json-ld
  docs/examples/schemas/json-ld/exampleNumber.json-ld
  docs/examples/schemas/json-ld/exampleString.json-ld
  docs/examples/schemas/json/exampleBoolean.json
  docs/examples/schemas/json/exampleDate.json
  docs/examples/schemas/json/exampleEmployee.json
  docs/examples/schemas/json/exampleInteger.json
  docs/examples/schemas/json/exampleNumber.json
  docs/examples/schemas/json/exampleString.json
Labels: documentation, backend

#388 feat: Partial did search in get credentials.
  internal/api_ui/server_test.go
  internal/repositories/claims.go
Labels: improvement, backend

#395 fix: Api version
  api/api.yaml
  api_ui/api.yaml
Labels: documentation, backend

#393 chore: improve logs in credential creation
  internal/core/services/claims.go
Labels: improvement, backend

#392 fix: UI package alignments & 1 high-severity vulnerability
  ui/package-lock.json
  ui/package.json
Labels: frontend

#394 chore: removed redundancies, improved component reuse & consolidated copy
  ui/src/components/credentials/AttributeBreadcrumb.tsx
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/CredentialIssuedQR.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/CredentialQR.tsx
  ui/src/components/credentials/ObjectAttributeValueTreeNode.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/schemas/DownloadSchema.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemaTreeNode.tsx
  ui/src/components/schemas/SchemasTable.tsx
Labels: frontend

#396 Update @iden3/eslint-config-react-ts package
  ui/package-lock.json
  ui/package.json
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/api/index.ts
  ui/src/adapters/env.ts
  ui/src/adapters/index.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/contexts/IssuerState.tsx
  ui/src/domain/connection.ts
  ui/src/domain/credential.ts
  ui/src/domain/env.ts
  ui/src/domain/error.ts
  ui/src/domain/issuer-state.ts
  ui/src/domain/jsonSchema.ts
  ui/src/domain/schema.ts
  ui/src/styles/theme.ts
  ui/src/utils/async.ts
Labels: frontend

#402 chore: update Dockerfile-arm.
  Dockerfile-arm
Labels: enhancement, backend

#399 feat: UI optional build tag config
  .env-ui.sample
  ui/.env.sample
  ui/scripts/deploy.sh
  ui/src/adapters/env.ts
  ui/src/components/credentials/CredentialQR.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/components/shared/UserDisplay.tsx
  ui/src/domain/env.ts
Labels: frontend

#405 fix: validating xsd:date types in link creation
  .github/workflows/checks.yml
  Makefile
  infrastructure/local/docker-compose-infra.yml
  infrastructure/local/test_data/schema/json-ld/exampleMultidepth.jsonld
  infrastructure/local/test_data/schema/json/exampleMultidepth.json
  internal/jsonschema/schema.go
  internal/jsonschema/schema_test.go
Labels: bug, backend

#407 fix: wrong issuer initialiser sample config vars
  .env-api.sample
  Makefile
Labels: bug, backend

#403 feat: Responsive UI
  ui/src/assets/icons/menu-01.svg
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/connections/CredentialsTable.tsx
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/Credentials.tsx
  ui/src/components/credentials/CredentialsTable.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/ObjectAttributeValueTreeNode.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/layouts/SiderLayout.tsx
  ui/src/components/schemas/Schemas.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/components/shared/CredentialDeleteModal.tsx
  ui/src/components/shared/Detail.tsx
  ui/src/components/shared/SiderLayoutContent.tsx
  ui/src/components/shared/SiderMenu.tsx
  ui/src/components/shared/TableCard.tsx
  ui/src/styles/index.scss
  ui/src/styles/theme.ts
  ui/src/styles/variables.module.scss
Labels: frontend

#401 feat: Implement form data validation against the JSON schema definition
  ui/package-lock.json
  ui/package.json
  ui/public/test-schema.json
  ui/public/test-schema.jsonld
  ui/public/test-schemas/employee.json
  ui/public/test-schemas/employee.jsonld
  ui/src/adapters/jsonSchemas.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/adapters/parsers/jsonSchemas.ts
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinkDetails.tsx
  ui/src/components/credentials/ObjectAttributeForm.tsx
  ui/src/components/credentials/ObjectAttributeValueTreeNode.tsx
  ui/src/components/credentials/attributes/Boolean.tsx
  ui/src/components/credentials/attributes/Number.tsx
  ui/src/components/credentials/attributes/String.tsx
  ui/src/components/schemas/ImportSchema.tsx
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/JSONHighlighter.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemaTree.tsx
  ui/src/components/schemas/SchemaViewer.tsx
  ui/src/domain/index.ts
  ui/src/domain/json.ts
  ui/src/domain/jsonSchema.ts
  ui/src/utils/error.ts
  ui/src/utils/jsonSchemas.ts
  ui/src/utils/types.ts
Labels: frontend

#406 feat: Search for partial words in schema attributes and type
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/domain/schema.go
  internal/core/ports/link_service.go
  internal/core/services/schema.go
  internal/core/services/tests/schema_test.go
  internal/db/schema/migrations/202305111652000_remove_schema_attributes.sql
  internal/repositories/claims.go
  internal/repositories/connections.go
  internal/repositories/ftsutil.go
  internal/repositories/ftsutil_test.go
  internal/repositories/link_repository.go
  internal/repositories/schema.go
  internal/repositories/tests/link_test.go
  internal/repositories/tests/schema_test.go
Labels: improvement, backend

#411 fix: Ant usage deprecation warnings.
  ui/src/components/connections/ConnectionDeleteModal.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinkDeleteModal.tsx
  ui/src/components/credentials/LinksTable.tsx
  ui/src/components/credentials/Summary.tsx
  ui/src/components/issuer-state/IssuerState.tsx
  ui/src/components/schemas/DownloadSchema.tsx
  ui/src/components/schemas/ImportSchema.tsx
  ui/src/components/shared/CredentialDeleteModal.tsx
  ui/src/components/shared/CredentialRevokeModal.tsx
  ui/src/contexts/IssuerState.tsx
  ui/src/styles/index.scss
Labels: frontend

#416 feat: adding retry publish identity state in issuer-api
  api/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
Labels: backend
