Repository 0xPolygonID/issuer-node, pull requests merged in 2023-06, with the labels that each got.

#418 Pid 885 create endpoint to return issuer node configuration
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/config_handler.go
  internal/api_ui/api.gen.go
  internal/api_ui/config_handler.go
  internal/common/helpers.go
Labels: backend

#426 Load token vault and did from k8s mounted volume
  Dockerfile-arm
  cmd/issuer_initializer/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  internal/config/config.go
Labels: backend

#427 chore: add k8s files
  k8s/Readme.md
  k8s/files/Makefile
  k8s/files/ingress.yaml
  k8s/files/issuer-node-api-configmap.yaml
  k8s/files/issuer-node-api-deployment.yaml
  k8s/files/issuer-node-api-service.yaml
  k8s/files/issuer-node-api-ui-configmap.yaml
  k8s/files/issuer-node-api-ui-deployment.yaml
  k8s/files/issuer-node-api-ui-service.yaml
  k8s/files/issuer-node-notifications.yaml
  k8s/files/issuer-node-pending-publisher.yaml
  k8s/files/issuer-node-pv.yaml
  k8s/files/issuer-node-ui-configmap.yaml
  k8s/files/issuer-node-ui-deployment.yaml
  k8s/files/issuer-node-ui-service.yaml
  k8s/files/postgres-configmap.yaml
  k8s/files/postgres-deployment.yaml
  k8s/files/postgres-pv.yaml
  k8s/files/postgres-service.yaml
  k8s/files/redis-deployment.yaml
  k8s/files/redis-service.yaml
  k8s/files/vault-configmap.yaml
  k8s/files/vault-deployment.yaml
  k8s/files/vault-pv.yaml
  k8s/files/vault-service.yaml
Labels: backend

#425 feat: Support schemas with IPFS links. Update go iden 3 libraries for IPFS.
  .env-issuer.sample
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  go.mod
  go.sum
  internal/api/main_test.go
  internal/api/server_test.go
  internal/api_ui/main_test.go
  internal/api_ui/server_test.go
  internal/api_ui/testdata/ipfs-ldcontext.json
  internal/api_ui/testdata/ipfs-schema.json
  internal/common/util.go
  internal/config/config.go
  internal/core/services/claims.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/core/services/tests/main_test.go
  internal/core/services/tests/notification_test.go
  internal/loader/ipfs.go
  internal/loader/ipfs_test.go
  internal/loader/multiprotocol.go
Labels: backend

#428 chore: Update slog library
  go.mod
  go.sum
  internal/log/log.go
Labels: improvement, backend

#423 fix: Test and integration
  .env-ui.sample
  ui/.env.sample
  ui/scripts/deploy.sh
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/env.ts
  ui/src/adapters/index.ts
  ui/src/adapters/jsonSchemas.ts
  ui/src/adapters/parsers/jsonSchemas.ts
  ui/src/components/schemas/ImportSchemaForm.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/Schemas.tsx
  ui/src/components/shared/SiderLayoutContent.tsx
  ui/src/contexts/Env.tsx
  ui/src/domain/env.ts
Labels: frontend

#424 refactor: Port last domain changes
  ui/package-lock.json
  ui/package.json
  ui/src/adapters/api/schemas.ts
  ui/src/adapters/jsonSchemas.ts
  ui/src/adapters/parsers/jsonSchemas.ts
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/schemas/SchemasTable.tsx
  ui/src/domain/index.ts
  ui/src/domain/jsonSchema.ts
  ui/src/utils/jsonSchemas.ts
  ui/src/vite-env.d.ts
  ui/tsconfig.json
Labels: frontend

#430 fix: set default IPFS gateway
  internal/config/config.go
Labels: improvement, backend

#400 chore: Use alpine for intel-amd architecture
  Dockerfile
Labels: backend

#437 fix: IPFS schemas not accepted when creating links
  cmd/platform_ui/main.go
  internal/api_ui/server_test.go
  internal/core/services/link.go
  internal/core/services/tests/link_test.go
  internal/jsonschema/schema.go
  internal/jsonschema/schema_test.go
Labels: bug, backend
