Repository 0xPolygonID/issuer-node, pull requests merged in 2023-10, with the labels that each got.

#498 chore: removing version verification when importing schema
  internal/api_ui/server.go
Labels: backend

#487 fix: avoid accessing nil metadata creating credential
  internal/core/services/claims.go
Labels: bug, backend

#497 Update credential with member
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  internal/api_ui/server.go
  internal/providers/vault.go
Labels: enhancement, backend

#501 chore: force credential description to campaign
  go.mod
  go.sum
  internal/core/services/claims.go
  pkg/notifications/messages.go
Labels: backend

#500 fix: Fix a bug making form values to be removed after typing
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/styles/theme.ts
Labels: bug, frontend
