Repository 0xPolygonID/issuer-node, pull requests merged in 2024-09, with the labels that each got.

#761 feat: improve sort filters in State transitions list
  api/api.yaml
  internal/api/api.gen.go
  internal/api/state.go
  internal/api/state_test.go
  internal/core/ports/claims_service.go
  internal/repositories/identity_state.go
Labels: enhancement, backend

#766 Feat: Universal links
  api/api.yaml
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  internal/api/api.gen.go
  internal/api/credentials.go
  internal/api/credentials_test.go
  internal/api/links.go
  internal/api/links_test.go
  internal/api/main_test.go
  internal/config/config.go
  internal/core/ports/claims_service.go
  internal/core/ports/link_service.go
  internal/core/ports/qrstore_service.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/identity_test.go
  internal/core/services/link.go
  internal/core/services/link_test.go
  internal/core/services/notification_test.go
  internal/core/services/qrstore.go
Labels: backend

#769 chore: Update go modules, go version, linter
  .github/workflows/demo_deploy_backend.yml
  .github/workflows/deploy_backend_v2.yml
  .github/workflows/test_deploy_backend.yml
  .golangci.yml
  Dockerfile
  Dockerfile-kms-importer
  go.mod
  go.sum
  internal/repositories/claims_test.go
Labels: backend

#686 Pid 2289 support jws packer
  .env-issuer.sample
  cmd/platform/main.go
  internal/config/config.go
  pkg/protocol/package_manager.go
  pkg/protocol/package_manager_test.go
  pkg/protocol/universal_DID_Resolver.go
  pkg/protocol/verify.go
Labels: enhancement, backend, do not merge
