Repository 0xPolygonID/issuer-node, pull requests merged in 2024-02, with the labels that each got.

#618 chore: add schema_type_description when claims are returned
  internal/repositories/claims.go
  internal/repositories/tests/claims_test.go
Labels: enhancement, backend

#620 chore: add RHS info to config endpoint
  internal/api/config_handler.go
  internal/api_ui/config_handler.go
Labels: enhancement, backend

#621 chore: remove schema_type_description
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/core/domain/claim.go
  internal/core/services/claims.go
  internal/db/schema/migrations/202402230818397_remove_schema_type_description_to_claims.sql
  internal/repositories/claims.go
Labels: enhancement, backend

#622 chore: updating open-api to v2
  Makefile
  api/api.yaml
  api/spec.html
  api_ui/api.yaml
  api_ui/spec.html
  go.mod
  go.sum
  internal/api/api.gen.go
  internal/api_ui/api.gen.go
Labels: backend

#589 chore: Update go version to 1.21 and use standard slog
  Dockerfile
  cmd/issuer_initializer/main.go
  cmd/migrate/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  go.mod
  go.sum
  internal/api/main_test.go
  internal/api/middleware.go
  internal/api/server_test.go
  internal/api_ui/main_test.go
  internal/api_ui/middleware.go
  internal/api_ui/server_test.go
  internal/core/services/claims.go
  internal/core/services/identity.go
  internal/core/services/tests/main_test.go
  internal/core/services/tests/notification_test.go
  internal/gateways/publisher.go
  internal/loader/cache.go
  internal/log/log.go
  internal/repositories/tests/main_test.go
  pkg/http/client.go
  tools/vault-migrator/main.go
Labels: backend, do not merge

#624 fix: Pagination in connections
  cmd/notifications/main.go
  cmd/platform_ui/main.go
  internal/api_ui/responses.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_repository.go
  internal/core/ports/connections_repository.go
  internal/core/ports/connections_service.go
  internal/core/services/connections.go
  internal/core/services/tests/notification_test.go
  internal/repositories/claims.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
Labels: bug, backend

#615 chore: allows scanning same credential link
  internal/core/services/link.go
  internal/core/services/tests/link_test.go
  internal/db/schema/migrations/202402160649030_add_update_at_column_user_authentication.sql
  internal/repositories/connections.go
Labels: enhancement, backend
