Repository 0xPolygonID/issuer-node, pull requests merged in 2024-10, with the labels that each got.

#803 feat: display name cannot be duplicated when creating identity
  api/api.yaml
  internal/api/api.gen.go
  internal/api/identity.go
  internal/api/identity_test.go
  internal/core/services/identity.go
  internal/db/schema/migrations/202410021258180_identities_display_name_set_to_unique.sql
  internal/repositories/identity.go
  internal/repositories/schema.go
  internal/repositories/schema_test.go
Labels: enhancement, backend

#802 chore: add schema cache to w3c doc loader
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  internal/api/main_test.go
  internal/config/config.go
  internal/core/services/main_test.go
  internal/jsonschema/schema_test.go
  internal/loader/loader.go
  internal/loader/w3CDocumentLoader_test.go
  internal/loader/w3c_loader.go
Labels: enhancement

#794 Improve revocation status validation
  internal/api/credentials.go
  internal/api/identity.go
Labels: enhancement

#815 chore: remove doas from dockerfile
  Dockerfile
Labels: enhancement

#817 feat: Rename qrCode wording to message name in API endpoints, requests and response
  api/api.yaml
  internal/api/api.gen.go
  internal/api/authentication.go
  internal/api/authentication_test.go
  internal/api/credentials.go
  internal/api/credentials_test.go
  internal/api/links.go
  internal/api/links_test.go
  ui/src/adapters/api/credentials.ts
Labels: frontend, backend

#831 Use schemas docs URL in explainer
  ui/src/components/schemas/Schemas.tsx
  ui/src/utils/constants.ts
Labels: frontend

#836 feat: Accepted rhs modes in supported networks endpoint
  api/api.yaml
  internal/api/api.gen.go
  internal/api/credentials.go
  internal/api/identity.go
  internal/api/networks.go
  internal/api/networks_test.go
  internal/network/resolver.go
  ui/src/adapters/api/identities.ts
  ui/src/components/identities/IdentityForm.tsx
  ui/src/domain/identity.ts
  ui/src/domain/index.ts
Labels: frontend, backend
