Repository 0xPolygonID/issuer-node, pull requests merged in 2024-01, with the labels that each got.

#588 feat: Order parameter in get connections endpoint
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_service.go
  internal/core/ports/connections_service.go
  internal/repositories/connections.go
  internal/sqltools/orderbyfilter.go
Labels: backend

#597 feat: Update multiformats/go-multiaddr version
  go.mod
  go.sum
Labels: backend

#592 Pid 1649 credential included in state of issuer even if only sig proof is selected
  internal/api_ui/server.go
  internal/core/services/identity.go
  internal/core/services/tests/identity_test.go
  internal/repositories/claims.go
Labels: bug

#602 chore: updating go-schema-processor library
  go.mod
  go.sum
  internal/loader/w3c_loader.go
Labels: backend

#594 feat: adding revoke push notification
  cmd/notifications/main.go
  internal/core/event/event.go
  internal/core/ports/claims_repository.go
  internal/core/ports/claims_service.go
  internal/core/ports/notification_service.go
  internal/core/services/claims.go
  internal/core/services/notification.go
  internal/gateways/publisher.go
  internal/repositories/claims.go
  pkg/notifications/messages.go
Labels: backend

#596 feat: add qr code switcher to the issuer node
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/connections_service.go
  internal/repositories/connections.go
  internal/repositories/tests/connections_test.go
  pkg/pagination/pagination.go
  ui/src/adapters/api/connections.ts
  ui/src/adapters/api/credentials.ts
  ui/src/components/connections/ConnectionsTable.tsx
  ui/src/components/credentials/CredentialIssuedQR.tsx
  ui/src/components/credentials/CredentialLinkQR.tsx
  ui/src/components/credentials/CredentialQR.tsx
  ui/src/components/credentials/IssuanceMethodForm.tsx
  ui/src/domain/credential.ts
Labels: frontend, backend

#605 chore: Refactor create Claims guard function
  internal/core/services/claims.go
Labels: backend

#607 fix: add revoked credentials to publish state action
  internal/repositories/claims.go
Labels: bug

#609 fix: get state status endpoint
  internal/api_ui/server_test.go
  internal/repositories/identity.go
Labels: bug

#608 chore: Update vite version
  ui/package-lock.json
  ui/package.json
Labels: frontend

#604 feat: UI can create credentials with refresh service field
  api_ui/api.yaml
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  ui/src/adapters/api/credentials.ts
  ui/src/adapters/parsers/forms.ts
  ui/src/components/credentials/CredentialDetails.tsx
  ui/src/components/credentials/IssueCredential.tsx
  ui/src/components/credentials/IssueCredentialForm.tsx
  ui/src/components/credentials/LinkDetails.tsx
  ui/src/components/schemas/ImportSchemaPreview.tsx
  ui/src/components/schemas/SchemaDetails.tsx
  ui/src/components/shared/Detail.tsx
  ui/src/domain/credential.ts
  ui/src/domain/index.ts
Labels: frontend

#591 chore: avoid fetching credentials with empty mtp proofs
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/domain/claim.go
  internal/core/services/claims.go
Labels: backend

#595 Support display method
  .golangci.yml
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/api.gen.go
  internal/api_ui/responses.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/domain/link.go
  internal/core/ports/claims_service.go
  internal/core/ports/link_service.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/db/schema/migrations/20240111024427_add_display_method_to_link_table.sql
  internal/repositories/link_repository.go
  internal/repositories/tests/claims_test.go
  internal/repositories/tests/link_test.go
Labels: backend

#606 chore: add health check endpoint
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  infrastructure/local/docker-compose.yml
Labels: enhancement
