Repository 0xPolygonID/issuer-node, pull requests merged in 2024-07, with the labels that each got.

#683 chore: remove unnecessary checking
  cmd/pending_publisher/main.go
Labels: enhancement, backend

#603 feat: Multichain support configuration
  .env-issuer.sample
  .gitignore
  .golangci.yml
  Dockerfile
  Makefile
  cmd/issuer_initializer/main.go
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  cmd/platform_ui/main.go
  go.mod
  internal/api/api.gen.go
  internal/api/config_handler.go
  internal/api/main_test.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/config_handler.go
  internal/api_ui/main_test.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/common/common.go
  internal/config/config.go
  internal/config/credential_status.go
  internal/core/domain/identity.go
  internal/core/ports/publisher.go
  internal/core/ports/transaction_service.go
  internal/core/services/account.go
  internal/core/services/did_registrator.go
  internal/core/services/identity.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/core/services/tests/main_test.go
  internal/core/services/tests/notification_test.go
  internal/gateways/onchain_credential_status_resolver.go
  internal/gateways/publisher.go
  internal/gateways/publisher_gateway.go
  internal/gateways/transaction.go
  internal/gateways/utils.go
  internal/providers/blockchain/eth.go
  pkg/blockchain/eth/client.go
  pkg/blockchain/eth/state.go
  pkg/credentials/revocation_status/iden3_onchain_sparse_merkletree_proof2023_resolver.go
  pkg/credentials/revocation_status/iden3_reverse_sparse_merkletree_proof_resolver.go
  pkg/credentials/revocation_status/iden3_revocation_status_v1.go
  pkg/credentials/revocation_status/resolver.go
  pkg/credentials/revocation_status/resolver_test.go
  pkg/helpers/read_file.go
  pkg/network/reader.go
  pkg/network/resolver.go
  pkg/protocol/packagemanager.go
  pkg/protocol/verify.go
  pkg/reverse_hash/factory.go
  resolvers_settings_sample.yaml
Labels: enhancement, backend, do not merge

#685 chore: add kms local storage
  .env-issuer.sample
  Makefile
  README.md
  cmd/kms_local_storage_priv_key_importer/main.go
  cmd/platform/main.go
  infrastructure/local/docker-compose.yml
  internal/config/config.go
  internal/core/services/identity.go
  internal/kms/kms.go
  internal/kms/local_storage_bjj_key_provider.go
  internal/kms/local_storage_eth_key_provider.go
  internal/kms/local_storage_utils.go
  internal/kms/local_storage_utils_test.go
  internal/kms/vault_bjj_key_provider.go
  internal/kms/vault_eth_key_provider.go
  internal/kms/vault_providers_helpers.go
Labels: enhancement, backend

#688 chore: add id parameter when claim is created
  api/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api/server_test.go
  internal/api_ui/server.go
  internal/api_ui/server_test.go
  internal/core/ports/claims_service.go
  internal/core/services/claims.go
  internal/core/services/link.go
  internal/core/services/tests/identity_test.go
  internal/core/services/tests/link_test.go
  internal/repositories/tests/claims_test.go
Labels: enhancement, backend

#689 feat: Rename claims endpoints to credential endpoints
  .github/workflows/golangci-lint.yml
  api/api.yaml
  internal/api/api.gen.go
  internal/api/server.go
  internal/api/server_test.go
  internal/core/services/identity.go
  internal/db/tests/claims_fixture.go
Labels: enhancement, backend

#692 feat: Move authentication endpoints to Core API
  api/api.yaml
  cmd/platform/main.go
  internal/api/api.gen.go
  internal/api/authentication.go
  internal/api/authentication_test.go
  internal/api/credentials.go
  internal/api/credentials_test.go
  internal/api/identity_test.go
  internal/api/main_test.go
  internal/api/server.go
  internal/api_ui/main_test.go
  internal/api_ui/server.go
  internal/core/services/claims.go
Labels: help wanted, backend

#694 feat: Move schema endpoits to core API
  api/api.yaml
  api_ui/api.yaml
  cmd/platform/main.go
  internal/api/api.gen.go
  internal/api/authentication_test.go
  internal/api/credentials_test.go
  internal/api/error.go
  internal/api/identity_test.go
  internal/api/main_test.go
  internal/api/responses.go
  internal/api/schemas.go
  internal/api/schemas_test.go
  internal/api/server.go
  internal/config/config.go
Labels: enhancement, backend

#693 feat: Add Mode All and support credential statuses on API level
  api/api.yaml
  api_ui/api.yaml
  internal/api/api.gen.go
  internal/api/credentials.go
  internal/api/identity.go
  internal/api/identity_test.go
  internal/api_ui/api.gen.go
  internal/api_ui/server.go
  internal/config/config.go
  internal/core/services/identity.go
  pkg/network/resolver.go
  pkg/reverse_hash/factory.go
  resolvers_settings_sample.yaml
Labels: enhancement, backend

#695 feat: Link management endpoints moved to core API
  api/api.yaml
  cmd/platform/main.go
  cmd/platform_ui/main.go
  internal/api/api.gen.go
  internal/api/authentication.go
  internal/api/authentication_test.go
  internal/api/links.go
  internal/api/links_test.go
  internal/api/main_test.go
  internal/api/responses.go
  internal/api/server.go
  internal/api_ui/server_test.go
  internal/core/services/link.go
  internal/core/services/tests/link_test.go
Labels: enhancement, backend

#696 feat: Connections endpoints moved to core API
  api/api.yaml
  internal/api/api.gen.go
  internal/api/connections.go
  internal/api/connections_test.go
  internal/api/responses.go
Labels: enhancement, backend

#704 chore: remove config property
  internal/config/config.go
Labels: backend

#705 chore: code refactoring
  cmd/notifications/main.go
  cmd/pending_publisher/main.go
  cmd/platform/main.go
  internal/api/main_test.go
  internal/api_ui/main_test.go
  internal/config/config.go
  internal/core/services/tests/main_test.go
  internal/kms/main_test.go
  internal/kms/vaultPluginIden3KeyProvider_test.go
  internal/providers/vault.go
Labels: enhancement, backend
